project_id = "rwbnynjpaimdfxqoqbvt"

[functions.delete-rulebook]
verify_jwt = true

[functions.serve-rulebook]
verify_jwt = false

[functions.import-jumps-csv]
verify_jwt = true

[functions.import-criteria-csv]
verify_jwt = true

[functions.import-balances-csv]
verify_jwt = true

[functions.import-rotations-csv]
verify_jwt = true

[functions.import-hoop-bases-csv]
verify_jwt = true

[functions.import-ball-bases-csv]
verify_jwt = true

[functions.import-clubs-bases-csv]
verify_jwt = true

[functions.import-ribbon-bases-csv]
verify_jwt = true

[functions.import-hoop-technical-elements-csv]
verify_jwt = true

[functions.import-clubs-technical-elements-csv]
verify_jwt = true

[functions.import-ribbon-technical-elements-csv]
verify_jwt = true

[functions.import-ball-technical-elements-csv]
verify_jwt = true

[functions.import-control-tables-csv]
verify_jwt = true

[functions.import-da-comments-csv]
verify_jwt = true

[functions.import-dynamic-catches-csv]
verify_jwt = true

[functions.import-dynamic-throws-csv]
verify_jwt = true

[functions.import-dynamic-general-criteria-csv]
verify_jwt = true

[functions.import-jumps-dbs-for-risks-csv]
verify_jwt = true

[functions.import-rotations-dbs-for-risks-csv]
verify_jwt = true

[functions.import-dbs-for-risks-csv]
verify_jwt = true

[functions.import-vertical-rotations-csv]
verify_jwt = true

[functions.import-prerecorded-risks-csv]
verify_jwt = true

[functions.import-prerecorded-risks-main-csv]
verify_jwt = true

[functions.import-pre-acrobatic-elements-csv]
verify_jwt = true
